#pragma once

enum TextureSlot {
    SLOT_BUILDINGS_HIGHLIGHT = 18,
    SLOT_BACKGROUND = 19,
    SLOT_UI_CURSOR = 20,
    SLOT_UI_MENU_BG = 21,
    SLOT_UI_MENU_CELL = 22,
    SLOT_UI_MENU_ICON = 23,
    SLOT_STREETS = 24,
    SLOT_UI_TOWNHALL_PANEL = 25,
    SLOT_UI_ROAD_BG = 26,
    SLOT_UI_ROAD_CELL = 27,
    SLOT_UI_ROAD_ICON = 28,
    SLOT_UNITS = 29,
    SLOT_FLAG_RESOURCES = 30,
};
