[XNetConfig_Configs]
LocalDHCP
TestLabStaticIP
;AutoApply


[Sample]
config_abEnet=             ;Specify spoofed MAC address ("xxxxxxxxxxxx") or empty to use default
config_ina=                ;Specify static IP address ("nnn.nnn.nnn.nnn") or 0 to use DHCP
config_inaMask=            ;Specify static subnet mask ("nnn.nnn.nnn.nnn")
config_inaGateway=         ;Specify static gateway ("nnn.nnn.nnn.nnn")
config_inaDnsServer1=      ;Specify primary static DNS server ("nnn.nnn.nnn.nnn")
config_inaDnsServer2=      ;Specify secondary static DNS server ("nnn.nnn.nnn.nnn")
config_achDhcpHostName=    ;Specify DHCP host name, or empty to not use
config_achPppoeUserName=   ;Specify PPPoE user name, or empty to not use
config_achPppoePassword=   ;Specify PPPoE password
config_achPppoeServer=     ;Specify PPPoE server
config_achPppoeService=    ;Specify PPPoE service
debug_ina=                 ;Specify static debug IP address ("nnn.nnn.nnn.nnn") or 0 to use DHCP
debug_inaMask=             ;Specify static debug subnet mask ("nnn.nnn.nnn.nnn")
debug_inaGateway=          ;Specify static debug gateway ("nnn.nnn.nnn.nnn")


;
;Example configuration that uses DHCP for all settings and turns off MAC
;spoofing, DHCP host name, and PPPoE.
;
[LocalDHCP]
config_abEnet=
config_ina=0
config_inaDnsServer1=0
config_achDhcpHostName=
config_achPppoeUserName=
debug_ina=0


;
;Example configuration that enables static IP address and DNS information.
;
[TestLabStaticIP]
config_ina=1.2.3.4
config_inaMask=255.255.255.0
config_inaGateway=1.2.3.1
config_inaDnsServer1=1.2.3.250
config_inaDnsServer2=1.2.3.251
debug_ina=1.2.3.5
debug_inaMask=255.255.255.0
debug_inaGateway=1.2.3.1


;
;Same as LocalDHCP except with the special AutoApply name.  If the AutoApply
;line under XNetConfig_Configs is uncommented, this section will always be
;configured any time XNetConfig is launched, as if it were specified on the
;command line.
;
[AutoApply]
config_abEnet=
config_ina=0
config_inaDnsServer1=0
config_achDhcpHostName=
config_achPppoeUserName=
debug_ina=0
